add_rules("mode.debug", "mode.release")
add_requires("glad", "glfw", "glm", "stb", "vulkan-headers")
add_requires("imgui v1.89-docking", { configs = {glfw_vulkan = true}})
add_requires("walnut 1.0")
target("WalnutApp")
    set_kind("binary")
    set_languages("cxx17")
    add_defines("WL_PLATFORM_WINDOWS", "WIN32")
    add_files("src/*.cpp")
    add_includedirs("src")
    add_links("vulkan-1")
    add_linkdirs("D:/lib/vulkan/1.3.216.0/Lib")
    add_packages("glad", "glfw", "glm", "stb", "imgui", "vulkan-headers", "walnut")
