package("walnut")
    add_urls("https://github.com/linuxing3/Walnut.git")
    add_versions("1.0", "4218af29ca6333ecf65791b4a1ae2de3f10e773a")
    add_versions("1.1", "4234726e1fa01411c7767b47761c9eaac74674ae")
    
    add_includedirs("include")
    
    on_install("windows", function (package)
        io.writefile("xmake.lua", [[
add_requires("glad", "glfw", "glm", "stb", "vulkan-headers")
add_requires("imgui v1.89-docking", { configs = {glfw_vulkan = true}})

target("walnut")
    set_kind("static")
    set_languages("cxx17")
    add_defines("WL_PLATFORM_WINDOWS")
    add_includedirs("Walnut/src")
    add_files("Walnut/src/Walnut/*.cpp", "Walnut/src/Walnut/Input/*.cpp")
    add_packages("glad", "glfw", "glm", "stb", "imgui", "vulkan-headers")
    --add_headerfiles("Walnut/src/Walnut/*.h", "Walnut/src/Walnut/Input/*.h")
    add_linkdirs("D:/lib/vulkan/1.3.216.0/Lib")
    add_links("vulkan-1")
]])
        os.mkdir("include")
        os.cp("Walnut/src/Walnut/*.h", package:installdir(path.join("include")))
        os.cp("Walnut/src/Walnut/Input/*.h", package:installdir(path.join("include")))
        import("package.tools.xmake").install(package)
    end)
package_end()